### ISSUE TITLE
학교/학급 정보 데이터 수집 / DB 초기화 / API

### ISSUE THREAD

**Issue by piper-hyowon** [project-baam/baam-server#5]
### ✅Task
- 학교 관련 데이터셋 모듈
        - 외부 서비스 어댑터: NEIS Open API Client
-  [X]  학교 기본 정보
- [X]   학급 정보

     - REST API _<회원가입시 활용>_
- [X]  초기 데이터 세팅 API(최초 1회 필요)
                        **POST** _/school-dataset/initialize_
-  [X] 모든 학교 목록 (이름 검색, 페이지네이션)
                        **GET** _/school-dataset/schools_
- [X] 학교별 학급 목록
                         **GET** _/school-dataset/classes/{schoolId}_
